# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.5.0
_src_path: gh:dafyddj/copier-docker-build
container_registry: docker.io
image_namespace: dafyddj
image_repo: ci-pre-commit
