# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.6.4
_src_path: gh:dafyddj/copier-docker-build
container_registry: docker.io
image_authors: SaltStack Formulas <GitHub @saltstack-formulas>
image_namespace: dafyddj
image_repo: ci-pre-commit
